version: '3.1'

services:
  postgres:
    image: postgres
    env_file:
      - database.env # configure postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - '5432:5432'
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
